import type { Task } from 'shared/model/types';

export const initialTasks: Task[] = [
  {
    id: '1',
    title: 'Исправить баг с логином',
    description: 'Проблема с повторным входом',
    category: 'Bug',
    status: 'In Progress',
    priority: 'High',
    createdAt: new Date('2025-07-12T14:25:00'),
  },
  {
    id: '2',
    title: 'Добавить возможность восстановления пароля',
    description: 'Пользователи должны иметь возможность восстанавливать пароль через email',
    category: 'Feature',
    status: 'To Do',
    priority: 'Medium',
    createdAt: new Date('2025-07-04T09:42:00'),
  },
  {
    id: '3',
    title: 'Обновить документацию по API',
    description: 'Добавить описание новых эндпоинтов',
    category: 'Documentation',
    status: 'Done',
    priority: 'Low',
    createdAt: new Date('2025-07-08T11:10:00'),
  },
  {
    id: '4',
    title: 'Рефакторинг компонента профиля',
    description: 'Упростить логику и улучшить читаемость кода',
    category: 'Refactor',
    status: 'In Progress',
    priority: 'Medium',
    createdAt: new Date('2025-07-01T16:35:00'),
  },
  {
    id: '5',
    title: 'Написать тесты для формы регистрации',
    description: 'Покрыть юнит-тестами все основные сценарии',
    category: 'Test',
    status: 'To Do',
    priority: 'High',
    createdAt: new Date('2025-07-10T08:15:00'),
  },
  {
    id: '6',
    title: 'Исправить отображение кнопок на мобильных устройствах',
    category: 'Bug',
    status: 'To Do',
    priority: 'Medium',
    createdAt: new Date('2025-07-03T12:20:00'),
  },
  {
    id: '7',
    title: 'Добавить темную тему',
    description: 'Реализовать переключение светлой и темной темы',
    category: 'Feature',
    status: 'In Progress',
    priority: 'High',
    createdAt: new Date('2025-07-14T17:55:00'),
  },
  {
    id: '8',
    title: 'Обновить зависимости проекта',
    description: 'Обновить библиотеки до последних стабильных версий',
    category: 'Refactor',
    status: 'Done',
    priority: 'Low',
    createdAt: new Date('2025-07-06T10:05:00'),
  },
];
